In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
X = iris.data
y = iris.target
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [7]:
N, d = X.shape

In [8]:
X[0,]

array([5.1, 3.5, 1.4, 0.2])

In [9]:
y[0]

0

In [25]:
from sklearn import neighbors
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, 
                                                    random_state = 666)
model = neighbors.KNeighborsClassifier(n_neighbors = 3)
model.fit(X_train, y_train)
y_test_pred = model.predict(X_test)

N_test = X_test.shape[0]
print (N_test)

50


In [26]:
from sklearn import metrics
print (1 - metrics.accuracy_score(y_test, y_test_pred))
print (np.mean(y_test != y_test_pred))

0.0
0.0


In [27]:
print (metrics.confusion_matrix(y_test, y_test_pred))

[[16  0  0]
 [ 0 19  0]
 [ 0  0 15]]
